test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin="christianadmin"
    args.site_name="MDL Archiv"